-- ============================================================
-- Schema: transactions
-- Source: Kaggle ULB Credit Card Fraud dataset (creditcard.csv)
--         (or synthetic stand-in generated by data/generate_synthetic.py)
-- ============================================================
-- Time    : seconds elapsed since the first transaction in the dataset
-- V1..V28 : PCA-anonymized features (no business meaning individually;
--           analyzed via correlation ranking, see 04_feature_correlation.sql)
-- Amount  : transaction amount (currency unspecified in source dataset)
-- Class   : 1 = fraud, 0 = legitimate
--
-- No merchant, location, or cardholder fields exist in this dataset --
-- all "business" dimensions below (Hour, DaySegment, AmountBand) are derived.
-- ============================================================

CREATE TABLE IF NOT EXISTS transactions (
    "Time"   REAL,
    "V1"     REAL, "V2" REAL, "V3" REAL, "V4" REAL, "V5" REAL,
    "V6"     REAL, "V7" REAL, "V8" REAL, "V9" REAL, "V10" REAL,
    "V11"    REAL, "V12" REAL, "V13" REAL, "V14" REAL, "V15" REAL,
    "V16"    REAL, "V17" REAL, "V18" REAL, "V19" REAL, "V20" REAL,
    "V21"    REAL, "V22" REAL, "V23" REAL, "V24" REAL, "V25" REAL,
    "V26"    REAL, "V27" REAL, "V28" REAL,
    "Amount" REAL,
    "Class"  INTEGER
);
